In [1]:
import numpy as np

In [2]:
X = np.array([[-2,3,-3],[2,-3,1],[0,0,-0.1],[1,2,-7]])

array([[0., 3., 0.],
       [2., 0., 1.],
       [0., 0., 0.],
       [1., 2., 0.]])

In [8]:
N = 4
outD = 10
grad = np.random.rand(4,3)
np.sum(grad,axis=0,keepdims=True).shape

(1, 3)

In [9]:
grad

array([[0.33891642, 0.65080448, 0.09313006],
       [0.42757779, 0.98410884, 0.81223989],
       [0.17369978, 0.78935451, 0.5501336 ],
       [0.74795524, 0.6058144 , 0.04820737]])

In [10]:
(X>0)*grad

array([[0.        , 0.65080448, 0.        ],
       [0.42757779, 0.        , 0.81223989],
       [0.        , 0.        , 0.        ],
       [0.74795524, 0.6058144 , 0.        ]])